export interface TtsVoiceOption {
  id: string;
  label: string;
  languageCodes: string[];
  gender: "MALE" | "FEMALE";
}

export const CHIRP3_HD_VOICES: TtsVoiceOption[] = [
  { id: "en-US-Chirp3-HD-Achernar", label: "Achernar (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Achird", label: "Achird (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Algenib", label: "Algenib (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Algieba", label: "Algieba (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Alnilam", label: "Alnilam (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Aoede", label: "Aoede (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Autonoe", label: "Autonoe (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Callirrhoe", label: "Callirrhoe (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Charon", label: "Charon (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Despina", label: "Despina (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Enceladus", label: "Enceladus (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Erinome", label: "Erinome (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Fenrir", label: "Fenrir (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Gacrux", label: "Gacrux (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Iapetus", label: "Iapetus (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Kore", label: "Kore (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Laomedeia", label: "Laomedeia (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Leda", label: "Leda (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Orus", label: "Orus (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Pulcherrima", label: "Pulcherrima (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Puck", label: "Puck (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Rasalgethi", label: "Rasalgethi (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Sadachbia", label: "Sadachbia (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Sadaltager", label: "Sadaltager (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Schedar", label: "Schedar (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Sulafat", label: "Sulafat (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Umbriel", label: "Umbriel (Male)", gender: "MALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Vindemiatrix", label: "Vindemiatrix (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Zephyr", label: "Zephyr (Female)", gender: "FEMALE", languageCodes: ["en-US"] },
  { id: "en-US-Chirp3-HD-Zubenelgenubi", label: "Zubenelgenubi (Male)", gender: "MALE", languageCodes: ["en-US"] },
];

export interface TtsLanguageOption {
  code: string;
  label: string;
}

export const CHIRP3_LANGUAGE_OPTIONS: TtsLanguageOption[] = [
  { code: "ar-XA", label: "Arabic (Generic)" },
  { code: "bn-IN", label: "Bengali (India)" },
  { code: "bg-BG", label: "Bulgarian (Bulgaria)" },
  { code: "yue-HK", label: "Chinese (Hong Kong)" },
  { code: "hr-HR", label: "Croatian (Croatia)" },
  { code: "cs-CZ", label: "Czech (Czech Republic)" },
  { code: "da-DK", label: "Danish (Denmark)" },
  { code: "nl-BE", label: "Dutch (Belgium)" },
  { code: "nl-NL", label: "Dutch (Netherlands)" },
  { code: "en-AU", label: "English (Australia)" },
  { code: "en-IN", label: "English (India)" },
  { code: "en-GB", label: "English (United Kingdom)" },
  { code: "en-US", label: "English (United States)" },
  { code: "et-EE", label: "Estonian (Estonia)" },
  { code: "fi-FI", label: "Finnish (Finland)" },
  { code: "fr-CA", label: "French (Canada)" },
  { code: "fr-FR", label: "French (France)" },
  { code: "de-DE", label: "German (Germany)" },
  { code: "el-GR", label: "Greek (Greece)" },
  { code: "gu-IN", label: "Gujarati (India)" },
  { code: "he-IL", label: "Hebrew (Israel)" },
  { code: "hi-IN", label: "Hindi (India)" },
  { code: "hu-HU", label: "Hungarian (Hungary)" },
  { code: "id-ID", label: "Indonesian (Indonesia)" },
  { code: "it-IT", label: "Italian (Italy)" },
  { code: "ja-JP", label: "Japanese (Japan)" },
  { code: "kn-IN", label: "Kannada (India)" },
  { code: "ko-KR", label: "Korean (South Korea)" },
  { code: "lv-LV", label: "Latvian (Latvia)" },
  { code: "lt-LT", label: "Lithuanian (Lithuania)" },
  { code: "ml-IN", label: "Malayalam (India)" },
  { code: "cmn-CN", label: "Mandarin Chinese (China)" },
  { code: "mr-IN", label: "Marathi (India)" },
  { code: "nb-NO", label: "Norwegian Bokmål (Norway)" },
  { code: "pl-PL", label: "Polish (Poland)" },
  { code: "pt-BR", label: "Portuguese (Brazil)" },
  { code: "pa-IN", label: "Punjabi (India)" },
  { code: "ro-RO", label: "Romanian (Romania)" },
  { code: "ru-RU", label: "Russian (Russia)" },
  { code: "sr-RS", label: "Serbian (Cyrillic)" },
  { code: "sk-SK", label: "Slovak (Slovakia)" },
  { code: "sl-SI", label: "Slovenian (Slovenia)" },
  { code: "es-ES", label: "Spanish (Spain)" },
  { code: "es-US", label: "Spanish (United States)" },
  { code: "sw-KE", label: "Swahili (Kenya)" },
  { code: "sv-SE", label: "Swedish (Sweden)" },
  { code: "ta-IN", label: "Tamil (India)" },
  { code: "te-IN", label: "Telugu (India)" },
  { code: "th-TH", label: "Thai (Thailand)" },
  { code: "tr-TR", label: "Turkish (Turkey)" },
  { code: "uk-UA", label: "Ukrainian (Ukraine)" },
  { code: "ur-IN", label: "Urdu (India)" },
  { code: "vi-VN", label: "Vietnamese (Vietnam)" },
];
