packages:
  - app
  - scene
  - scene-compiler
  - renderer
  - billing-service
  - packages/*

onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - msgpackr-extract
  - protobufjs
  - puppeteer
  - sharp
  - unrs-resolver
