'use client';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-[#0f0f12] via-[#0f0f12] to-[#1a1a1f]">
      {/* Navigation */}
      <nav className="sticky top-0 z-50 border-b border-slate-800 bg-[#0f0f12]/95 backdrop-blur">
        <div className="max-w-4xl mx-auto px-6 py-4">
          <a href="/" className="text-blue-400 hover:text-blue-300">← Back to Home</a>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-5xl font-bold text-white mb-12">Terms of Service</h1>

        <div className="prose prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
            <p className="text-slate-300 leading-relaxed">
              By accessing and using GeminiStudio, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">2. Source Code License</h2>
            <p className="text-slate-300 leading-relaxed mb-4">
              GeminiStudio source code is licensed under the <strong className="text-white">Elastic License 2.0 (ELv2)</strong>. This is a source-available license that permits you to view, use, and modify the code for personal and internal purposes.
            </p>
            <p className="text-slate-300 leading-relaxed mb-4">
              Under this license, you may NOT:
            </p>
            <ul className="list-disc list-inside text-slate-300 space-y-2">
              <li>Provide GeminiStudio to third parties as a hosted or managed service</li>
              <li>Offer GeminiStudio's functionality as a commercial SaaS product</li>
              <li>Remove or obscure any licensing, copyright, or other notices</li>
              <li>Circumvent any license key functionality in the software</li>
            </ul>
            <p className="text-slate-300 leading-relaxed mt-4">
              The full license text is available at: <a href="https://github.com/youneslaaroussi/geministudio/blob/main/LICENSE" className="text-blue-400 hover:text-blue-300">github.com/youneslaaroussi/geministudio</a>
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">3. Content Ownership</h2>
            <p className="text-slate-300 leading-relaxed mb-4">
              You retain all ownership rights to the video content you upload to GeminiStudio. By uploading content, you grant GeminiStudio a non-exclusive, worldwide, royalty-free license to use your content solely for the purpose of providing the Service.
            </p>
            <p className="text-slate-300 leading-relaxed">
              Edited videos created by GeminiStudio are the sole property of the user who commissioned them.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">4. AI-Generated Content</h2>
            <p className="text-slate-300 leading-relaxed mb-4">
              GeminiStudio uses Google's Gemini 3 AI model to create edited videos based on your input. While we strive for accuracy, we make no warranties regarding the output quality or accuracy of AI-generated content. You are responsible for reviewing and approving all edited videos before use.
            </p>
            <p className="text-slate-300 leading-relaxed">
              Content generated by AI models (such as AI-generated music, narration, or effects) is subject to the applicable third-party service provider's terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">5. Prohibited Uses</h2>
            <p className="text-slate-300 leading-relaxed">
              You may not use GeminiStudio to:
            </p>
            <ul className="list-disc list-inside text-slate-300 space-y-2 mt-3">
              <li>Create content that is derogatory, offensive, threatening, defamatory, or harassing</li>
              <li>Create content that infringes on third-party intellectual property rights</li>
              <li>Create content that violates any applicable law or regulation</li>
              <li>Create deepfakes or manipulated content intended to deceive</li>
              <li>Use the Service in any manner that could damage, disable, or impair the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">6. Credit System and Payments</h2>
            <p className="text-slate-300 leading-relaxed mb-4">
              GeminiStudio uses a credit-based system for video generation and editing operations. Credits may be purchased through Stripe and are non-refundable.
            </p>
            <p className="text-slate-300 leading-relaxed">
              We reserve the right to modify pricing, credit costs, and billing terms with notice. Continued use of the Service constitutes acceptance of modified terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">7. Limitation of Liability</h2>
            <p className="text-slate-300 leading-relaxed">
              The materials on GeminiStudio are provided "as is". GeminiStudio makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">8. Termination</h2>
            <p className="text-slate-300 leading-relaxed">
              We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason whatsoever, including if you breach the Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">9. Modifications to Service</h2>
            <p className="text-slate-300 leading-relaxed">
              GeminiStudio may modify or discontinue the Service (or any part thereof) at any time. We are not liable to you or to any third party for any modification, suspension, or discontinuance of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">10. Hackathon Competition</h2>
            <p className="text-slate-300 leading-relaxed mb-4">
              This version of GeminiStudio is submitted to the Google DeepMind Gemini 3 Hackathon competition. By using GeminiStudio during the hackathon period, you acknowledge that:
            </p>
            <ul className="list-disc list-inside text-slate-300 space-y-2 mt-3">
              <li>You consent to the collection and use of your project data for judging purposes</li>
              <li>Your generated content may be evaluated by hackathon judges</li>
              <li>The hackathon competition rules apply as outlined at Devpost</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">11. Governing Law</h2>
            <p className="text-slate-300 leading-relaxed">
              These terms and conditions are governed by and construed in accordance with the laws of California, United States, and you irrevocably submit to the exclusive jurisdiction of the courts located in California.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">12. Changes to Terms</h2>
            <p className="text-slate-300 leading-relaxed">
              GeminiStudio may revise these terms of service at any time without notice. By using this Service, you are agreeing to be bound by the then current version of these terms of service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">13. Contact</h2>
            <p className="text-slate-300 leading-relaxed">
              If you have any questions about these Terms of Service, please contact Younes Laaroussi at: hello@youneslaaroussi.ca
            </p>
          </section>

          <div className="border-t border-slate-800 pt-8 mt-12">
            <p className="text-slate-500 text-sm">
              Effective Date: January 31, 2026<br />
              Last Updated: January 31, 2026
            </p>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-slate-800 bg-slate-900/50 py-8 mt-16">
        <div className="max-w-4xl mx-auto px-6 text-center text-slate-500 text-sm">
          <p>© 2026 Younes Laaroussi · GeminiStudio | Licensed under Elastic License 2.0 (ELv2)</p>
        </div>
      </footer>
    </div>
  );
}
