/**
 * Reads @motion-canvas/2d and @motion-canvas/core .d.ts from node_modules
 * and writes app/app/lib/monaco-types-data.ts so Monaco can load them synchronously
 * (avoids "Cannot find module '@motion-canvas/core'" etc.).
 *
 * Run from repo root: pnpm exec tsx app/scripts/generate-motion-canvas-types.ts
 * Or from app: pnpm exec tsx scripts/generate-motion-canvas-types.ts
 */
import { readFileSync, existsSync, readdirSync, statSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const PACKAGES = ["@motion-canvas/2d", "@motion-canvas/core"] as const;

function collectDtsFiles(
  dir: string,
  relativeDir: string,
  pkg: string,
  out: { path: string; content: string }[]
): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const name of entries) {
    const fullPath = join(dir, name);
    const relativePath = relativeDir ? join(relativeDir, name) : name;
    const monacoPath = join("node_modules", pkg, relativePath).replace(/\\/g, "/");
    try {
      if (statSync(fullPath).isDirectory()) {
        collectDtsFiles(fullPath, relativePath, pkg, out);
      } else if (name.endsWith(".d.ts")) {
        const content = readFileSync(fullPath, "utf-8");
        out.push({ path: monacoPath, content });
      }
    } catch {
      // skip
    }
  }
}

function getPackageTypes(nodeModules: string, pkg: string): { path: string; content: string }[] {
  const libPath = join(nodeModules, pkg, "lib");
  if (!existsSync(libPath)) return [];
  const out: { path: string; content: string }[] = [];
  collectDtsFiles(libPath, "lib", pkg, out);
  return out;
}

const cwd = process.cwd();
// When run from repo root: cwd/app/node_modules has @motion-canvas. When run from app: cwd/node_modules has it.
const nodeModulesAtApp = join(cwd, "app", "node_modules");
const nodeModulesHere = join(cwd, "node_modules");
const nodeModules = existsSync(join(nodeModulesAtApp, "@motion-canvas", "2d"))
  ? nodeModulesAtApp
  : nodeModulesHere;
const outPath = nodeModules === nodeModulesAtApp
  ? join(cwd, "app", "app", "lib", "monaco-types-data.ts")
  : join(cwd, "app", "lib", "monaco-types-data.ts");

const files: { path: string; content: string }[] = [];

// Monaco's Node resolver looks for package.json to get "types" entry; add them first.
for (const pkg of PACKAGES) {
  const pkgPath = join(nodeModules, pkg);
  if (!existsSync(pkgPath)) {
    console.warn(`Skip ${pkg}: not found at ${pkgPath}`);
    continue;
  }
  const packageJsonPath = join(pkgPath, "package.json");
  if (existsSync(packageJsonPath)) {
    const pkgJson = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
    const types = pkgJson.types ?? pkgJson.typings ?? "./lib/index.d.ts";
    const virtualPath = join("node_modules", pkg, "package.json").replace(/\\/g, "/");
    files.push({
      path: virtualPath,
      content: JSON.stringify({ name: pkg, types }),
    });
  }
  files.push(...getPackageTypes(nodeModules, pkg));
}

console.log(`Collected ${files.length} .d.ts files`);

const lines = files.map(
  (f) => `  { path: ${JSON.stringify(f.path)}, content: ${JSON.stringify(f.content)} }`
);
const ts = `/** Generated by scripts/generate-motion-canvas-types.ts - do not edit manually */\n\nexport const MOTION_CANVAS_TYPES: { path: string; content: string }[] = [\n${lines.join(",\n")}\n];\n`;

mkdirSync(join(outPath, ".."), { recursive: true });
writeFileSync(outPath, ts, "utf-8");
console.log(`Wrote ${outPath}`);
process.exit(0);
